name: MacOS Clang Deployment

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest
    timeout-minutes: 10


    steps:
      - uses: actions/checkout@v2

      - name: Install gfortran and GCC
        run: brew install gfortran gcc@12
        
      - name: Configure CMAKE
        run: cmake -DGITHUB_ACTIONS=on -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
          FC: gfortran-12
  
      - name: Build
        run: |
             cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
             cd ${{github.workspace}}/build
             make TestQuTree        
  
      - name: Unit Tests
        working-directory: ${{github.workspace}}/build
        run: ./tests/TestQuTree
      
