name: Ubuntu GCC Deployment

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15


    steps:
      - uses: actions/checkout@v2
  
      - name: Install OpenBLAS and Lapack
        run: |
             sudo apt-get update
             sudo apt-get install -y libopenblas-dev liblapack-dev liblapacke-dev
      
      - name: Install GCC
        run: |
             sudo apt-get update
             sudo apt-get install -y g++-10 gcc-10

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Configure CMAKE
        run: cmake -DGITHUB_ACTIONS=on -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        shell: bash
        env:
          CC: gcc-10
          CXX: g++-10
      
      - name: Build
        run: |
             cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
             cd ${{github.workspace}}/build
             make TestQuTree
      
      - name: Unit Tests
        working-directory: ${{github.workspace}}/build
        run: ./tests/TestQuTree

      - name: Valgrind-Check Unit Tests
        continue-on-error: true
        if: always()
        working-directory: ${{github.workspace}}/build
        run: valgrind --leak-check=full --show-reachable=yes --track-origins=yes --error-exitcode=1 ./tests/TestQuTree
